FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev bash curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN python3 -m venv venv
RUN venv/bin/pip install --upgrade pip
RUN venv/bin/pip install poetry

COPY pyproject.toml poetry.lock ./
RUN venv/bin/poetry install --no-root

ENV PYTHONPATH=/app/quotes-parser-api
COPY . /app

CMD ["venv/bin/poetry", "run", "uvicorn", "quotes-parser-api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
